### ISSUE TITLE
questions abount data

### ISSUE THREAD

**Issue by yejr0229** [jimmyYliu/Animatable-3D-Gaussian#1]
Hi,I found the PeopleSnapshot dataset is different from the original one,in poses folder youi have anim_nerf_val.npz\anim_nerf_train.npz\anim_nerf_test.npz,are this the smpl paramaters?How did you get these?

**Comment by yejr0229** [comment]
Thanks for replying.Now I encounter another problem.
I use this command "python train.py --config-name peoplesnapshot.yaml dataset=peoplesnapshot/male-3-casual" to train successfully,but can't use this command to test "python test.py --config-name peoplesnapshot.yaml dataset=peoplesnapshot/male-3-casual",here is the detailed error:
CUDA_VISIBLE_DEVICES=1 python test.py --config-name peoplesnapshot.yaml dataset=peoplesnapshot/male-3-casual
Seed set to 0
Error executing job with overrides: ['dataset=peoplesnapshot/male-3-casual']
Traceback (most recent call last):
  File "test.py", line 18, in <module>
    main()
  File "/media/data4/yejr/conda_env/anim-gaussian/lib/python3.8/site-packages/hydra/main.py", line 94, in decorated_main
    _run_hydra(
  File "/media/data4/yejr/conda_env/anim-gaussian/lib/python3.8/site-packages/hydra/_internal/utils.py", line 394, in _run_hydra
    _run_app(
  File "/media/data4/yejr/conda_env/anim-gaussian/lib/python3.8/site-packages/hydra/_internal/utils.py", line 457, in _run_app
    run_and_report(
  File "/media/data4/yejr/conda_env/anim-gaussian/lib/python3.8/site-packages/hydra/_internal/utils.py", line 223, in run_and_report
    raise ex
  File "/media/data4/yejr/conda_env/anim-gaussian/lib/python3.8/site-packages/hydra/_internal/utils.py", line 220, in run_and_report
    return func()
  File "/media/data4/yejr/conda_env/anim-gaussian/lib/python3.8/site-packages/hydra/_internal/utils.py", line 458, in <lambda>
    lambda: hydra.run(
  File "/media/data4/yejr/conda_env/anim-gaussian/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 132, in run
    _ = ret.return_value
  File "/media/data4/yejr/conda_env/anim-gaussian/lib/python3.8/site-packages/hydra/core/utils.py", line 260, in return_value
    raise self._return_value
  File "/media/data4/yejr/conda_env/anim-gaussian/lib/python3.8/site-packages/hydra/core/utils.py", line 186, in run_job
    ret.return_value = task_function(task_cfg)
  File "test.py", line 10, in main
    model = NeRFModel.load_from_checkpoint('model.ckpt')
  File "/media/data4/yejr/conda_env/anim-gaussian/lib/python3.8/site-packages/pytorch_lightning/core/module.py", line 1552, in load_from_checkpoint
    loaded = _load_from_checkpoint(
  File "/media/data4/yejr/conda_env/anim-gaussian/lib/python3.8/site-packages/pytorch_lightning/core/saving.py", line 89, in _load_from_checkpoint
    model = _load_state(cls, checkpoint, strict=strict, **kwargs)
  File "/media/data4/yejr/conda_env/anim-gaussian/lib/python3.8/site-packages/pytorch_lightning/core/saving.py", line 156, in _load_state
    obj = cls(**_cls_kwargs)
TypeError: __init__() missing 1 required positional argument: 'opt'
Can you tell me how to deal with it?

**Comment by yejr0229** [comment]
Why the yaml file can't be read in test.py?I use the same arguments.

**Comment by jimmyYliu** [comment]
Can you check if your git repository is updated to the latest version? I did not find this problem in the latest version. You can also directly add the test code to the train.py file for testing.
